substitutions:
  device_name: esphome-igrill
  friendly_name: iGrill
  igrill_v2_name: 'Weber IGrill2'

esphome:
  name: '${device_name}'

esp32:
  board: nodemcu-32s
  framework:
    type: arduino
    version: recommended

# Enable logging
logger:
#  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_api_key

ota:
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
#  - source: github://allistermaguire/esphome-igrill@v1.2
  - source:
      type: local
      path: components

esp32_ble_tracker:
#igrill_ble_listener:

ble_client:
  - mac_address: 70:91:8F:17:1C:30
    id: igrill_v2
    on_connect:
      then:
        - binary_sensor.template.publish:
            id: v2_connection_bin
            state: ON
    on_disconnect:
      then:
        - binary_sensor.template.publish:
            id: v2_connection_bin
            state: OFF

button:
  - platform: restart
    name: 'Restart - ${friendly_name}'

# Sensors for ESP version and WIFI information
text_sensor:
  - platform: version
    hide_timestamp: true
    name: '${friendly_name} - ESPHome Version'
  - platform: wifi_info
    ip_address:
      name: '${friendly_name} - IP Address'
      icon: mdi:wifi
    ssid:
      name: '${friendly_name} - Connected SSID'
      icon: mdi:wifi-strength-2

sensor:
  # WiFi signal
  - platform: wifi_signal
    name: '${friendly_name} - WiFi Signal'
    update_interval: 120s
  - platform: igrill
    ble_client_id: igrill_v2
    update_interval: 30s # default
    send_value_when_unplugged: true # default
    unplugged_probe_value: 0 # default
    battery_level:
      name: '${igrill_v2_name} Battery'
    temperature_probe1:
      name: '${igrill_v2_name} Temp Probe 1'
    temperature_probe2:
      name: '${igrill_v2_name} Temp Probe 2'
    temperature_probe3:
      name: '${igrill_v2_name} Temp Probe 3'
    temperature_probe4:
      name: '${igrill_v2_name} Temp Probe 4'
 
binary_sensor:
  - platform: template
    name: '${igrill_v2_name} Connection Status'
    id: v2_connection_bin
    device_class: connectivity
    entity_category: diagnostic
